theme: jekyll-theme-minimal
title: [Daniel Morales Portfolio]
description: [I am a Finance Professional with 8 years experience in Fortune 500 Companies]
logo: [https://github.com/danielmc21/thefinancescientist/blob/main/profile-pic-5.png]
