theme: jekyll-theme-minimal
title: [Daniel Morales Portfolio]
description: I am a Finance Professional with 9 years experience in Finance in Fortune 500 Companies. Passion for Corporate Finance,  M&A,  Investments and Data Science. Msc. Finance & B.A. Accounting
logo: /img/ADVANCED-FINANCIAL-STATEMENT-ANALYSIS.jpeg
